#!/bin/bash
# See 60-dkms-install-zfs.hook

set -o errexit
set -o nounset
set -o xtrace

path=""
kernel_version=""

while read -r path; do
    echo "${path}"
    if [[ "${path}" =~ ^usr/lib/modules/([^/]+)/ ]]; then
	kernel_version="${BASH_REMATCH[1]}"
    fi
done

if [[ "${kernel_version}" != "" ]]; then

    for module in $(ls /usr/src); do
	if [[ "${module}" =~ ^spl-(.*)$ ]]; then
	    dkms install spl/"${BASH_REMATCH[1]}" -k "${kernel_version}"
	fi
    done

    for module in $(ls /usr/src); do
	if [[ "${module}" =~ ^zfs-(.*)$ ]]; then
	    dkms install zfs/"${BASH_REMATCH[1]}" -k "${kernel_version}"
	fi
    done
fi
