#!/bin/bash
# See 60-dkms-install-zfs.hook

set -o errexit
set -o nounset
set -o xtrace

install_module() {
    local module="${1}"
    local kernel="${2}"
    for m in $(ls /usr/src); do
	if [[ "${m}" =~ ^"${module}"-(.*)$ ]]; then
	    dkms install "${module}/${BASH_REMATCH[1]}" -k "${kernel}"
	fi
    done
}

for kernel in $(ls /usr/lib/modules); do
    install_module spl "${kernel}"
    install_module zfs "${kernel}"
done
